# This file was generated by GoReleaser. DO NOT EDIT.
cask "env-starter" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "a810666fc1090acd3248a3e52dc311529bce2ee2dcc7a7c71f11bd2b1bbbfdbf"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
    on_arm do
      sha256 "5ac4878d03c92d7a752dcd05effbc5ba5f913ede752eb11293b1c6b85db9c846"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e1b9166e6ce5fe942d9c61bac3ddf60e1764ad10fb5a6cce3346a42687adfd9e"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_linux_amd64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
    on_arm do
      sha256 "6586a2071fb6ebb927fe9562ad24d44cd9942f221ec8ebb64ebae09f5b25c0f6"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_linux_arm64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
  end

  name "env-starter"
  desc "Keyboard-driven TUI meta-launcher for developer environments"
  homepage "https://github.com/adericbourg/env-starter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env-starter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/env-starter"]
    end
  end

  # No zap stanza required

end
