# This file was generated by GoReleaser. DO NOT EDIT.
cask "env-starter" do
  version "1.6.3"

  on_macos do
    on_intel do
      sha256 "b016b38a0b4463c5f63af1385f779aaba0f18cb2a9cd12491630e18f416bae61"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
    on_arm do
      sha256 "c2208c964c279cf558f91df6ad0a5303cb0d3da63130f1b27ecf9e760d81f4b7"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
  end

  on_linux do
    on_intel do
      sha256 "59417b464c85432ab1599d6076000aeb0adf6909e3dfc324430821a0110b7ae5"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_linux_amd64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
    on_arm do
      sha256 "ff0ed96e5158fc9884d568a472b13d640bfb33c81066246c93cffd9ea84014cd"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_linux_arm64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
  end

  name "env-starter"
  desc "Keyboard-driven TUI meta-launcher for developer environments"
  homepage "https://github.com/adericbourg/env-starter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env-starter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/env-starter"]
    end
  end

  # No zap stanza required

end
