# This file was generated by GoReleaser. DO NOT EDIT.
cask "env-starter" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "afe63590283e87c9db6236a12126f3081219581c8052ef38b9889574413df36c"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
    on_arm do
      sha256 "151cd6a51cfd6752ca07a00f5e8c22a1cc7e242f2af8320386d902efc3c943cf"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae3967cf3c02adf47cd0fdc414847c36f6c621baeacbba6b5f0571beaae86394"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_linux_amd64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
    on_arm do
      sha256 "3981f1e83718210fbd41c242ce2aca6077657ce8db3b0c346bf078cd5be11556"
      url "https://github.com/adericbourg/env-starter/releases/download/v#{version}/env-starter_#{version}_linux_arm64.tar.gz",
        verified: "github.com/adericbourg/env-starter/"
    end
  end

  name "env-starter"
  desc "Keyboard-driven TUI meta-launcher for developer environments"
  homepage "https://github.com/adericbourg/env-starter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env-starter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/env-starter"]
    end
  end

  # No zap stanza required

end
