# This file is generated by madsister's release workflow. DO NOT EDIT.
cask "madsister-snapshot" do
  version "0.0.0-snapshot.43"
  sha256 "18c18d46be957c3f6a69ac3396691e8f8f40a5c2dad98eff3c560d7d3f15d17c"

  url "https://github.com/adericbourg/madsister/releases/download/v#{version}/madsister-snapshot_#{version}_aarch64.dmg"
  name "madsister-snapshot"
  desc "Turns a song into an editable, printable chord grid"
  homepage "https://github.com/adericbourg/madsister"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on arch: :arm64
  depends_on formula: "ffmpeg"

  app "madsister-snapshot.app"

  # Not signed nor notarized: without this Gatekeeper blocks the app.
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/madsister-snapshot.app"]
  end

  zap trash: "~/Library/Application Support/dev.dericbourg.madsister-snapshot"
end
